---
title: "1st markdowm"
author: "Jing Zhang"
date: "2018年5月17日"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

dowload sleep study data
```{r}
library(readr)
sleep <- read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv") # no spaces
head(sleep)
```

Plot the data by subject
```{r}
library(ggplot2)
ggplot(sleep, aes(x = Days, y=Reaction)) + geom_smooth() + scale_x_continuous(breaks=seq(0,8, by =2)) + facet_wrap(~Subject)

```

Summary statistics by subject
```{r}
library(dplyr)
sleep %>%
  group_by(Subject) %>%
  summary(mean(Reaction))
  
```


Mean centre reaction times and plot on a single axis
```{r}
sleep %>%
  group_by(Subject) %>%
  mutate(mean_centered_reaction = Reaction - mean(Reaction)) %>%
  ggplot(aes(x= Days, y=mean_centered_reaction, colour = factor(Subject))) +
  geom_smooth(show.legend = FALSE, se=FALSE) +
            scale_x_continuous(breaks=seq(0,8, by =2))
  
```








